version: '3.3'
services:
  survey:
    restart: unless-stopped
    build: .
    env_file:
      - .env
    volumes:
      - static_volume:/srv/repo/src/open_survey_tool/staticfiles
    expose:
      - "8080"
    depends_on: [ postgres ]

  postgres:
    restart: unless-stopped
    image: postgres:13.3
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    restart: unless-stopped
    build: nginx
    volumes:
      - static_volume:/srv/staticfiles
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - survey

volumes:
  static_volume:
  postgres_data:
